CC = g++

sampleEx2: exercise2_4.o exercise2_7.o exercise2_8.o exercise2_41.o exercise2_42_151.o exercise2_42_152.o exercise2_42_16.o

exercise2_4.o:
	g++ exercise2_4.cpp -std=c++11 -o exercise2_4 && ./exercise2_4

exercise2_7.o:
	g++ exercise2_7.cpp -std=c++11 -o exercise2_7 && ./exercise2_7

exercise2_8.o:
	g++ exercise2_8.cpp -std=c++11 -o exercise2_8 && ./exercise2_8

exercise2_41.o:
	g++ exercise2_41.cpp -std=c++11 -o exercise2_39 && ./exercise2_39

exercise2_42_151.o:
	g++ exercise2_42_151.cpp -std=c++11 -o exercise2_42_151 && ./exercise2_42_151

exercise2_42_152.o:
	g++ exercise2_42_152.cpp -std=c++11 -o exercise2_42_152 && ./exercise2_42_152

exercise2_42_16.o:
	g++ exercise2_42_16.cpp -std=c++11 -o exercise2_42_16 && ./exercise2_42_16
