CC = g++

exercise5: sum_of_digits.o prime_numbers.o linear_regression.o

sum_of_digits.o:
	g++ sum_of_digits.cpp -std=c++11 -o sum_of_digits && ./sum_of_digits

prime_numbers.o:
	g++ prime_numbers.cpp -std=c++11 -o sum_of_digits && ./sum_of_digits
	
linear_regression.o:
	g++ linear_regression.cpp -std=c++11 -o linear_regression && ./linear_regression
