CC = g++

sampleEx3: exercise3_1.o exercise3_2_1.o exercise3_2_2.o exercise3_4.o exercise3_5.o exercise3_6.o exercise3_7.o exercise3_8.o exercise3_10.o exercise3_14.o exercise3_15.o exercise3_16.o exercise3_20.o exercise3_21.o exercise3_21_2.o exercise3_22.o exercise3_24.o exercise3_25.o exercise3_31.o exercise3_32.o exercise3_35.o exercise3_36.o exercise3_41.o exercise3_43.o exercise3_44.o exercise3_45.o

exercise3_1.o:
	g++ exercise3_1.cpp -std=c++11 -o exercise3_1 && ./exercise3_1

exercise3_2_1.o:
	g++ exercise3_2_1.cpp -std=c++11 -o exercise3_2_1 && ./exercise3_2_1

exercise3_2_2.o:
	g++ exercise3_2_2.cpp -std=c++11 -o exercise3_2_2 && ./exercise3_2_2

exercise3_4.o:
	g++ exercise3_4.cpp -std=c++11 -o exercise3_4 && ./exercise3_4

exercise3_5.o:
	g++ exercise3_5.cpp -std=c++11 -o exercise3_5 && ./exercise3_5

exercise3_6.o:
	g++ exercise3_6.cpp -std=c++11 -o exercise3_6 && ./exercise3_6

exercise3_7.o:
	g++ exercise3_7.cpp -std=c++11 -o exercise3_7 && ./exercise3_7

exercise3_8.o:
	g++ exercise3_8.cpp -std=c++11 -o exercise3_8 && ./exercise3_8

exercise3_10.o:
	g++ exercise3_10.cpp -std=c++11 -o exercise3_10 && ./exercise3_10

exercise3_14.o:
	g++ exercise3_14.cpp -std=c++11 -o exercise3_14 && ./exercise3_14

exercise3_15.o:
	g++ exercise3_15.cpp -std=c++11 -o exercise3_15 && ./exercise3_15

exercise3_16.o:
	g++ exercise3_16.cpp -std=c++11 -o exercise3_16 && ./exercise3_16

exercise3_20.o:
	g++ exercise3_20.cpp -std=c++11 -o exercise3_20 && ./exercise3_20

exercise3_21.o:
	g++ exercise3_21.cpp -std=c++11 -o exercise3_21 && ./exercise3_21

exercise3_21_2.o:
	g++ exercise3_21_2.cpp -std=c++11 -o exercise3_21_2 && ./exercise3_21_2

exercise3_22.o:
	g++ exercise3_22.cpp -std=c++11 -o exercise3_22 && ./exercise3_22

exercise3_24.o:
	g++ exercise3_24.cpp -std=c++11 -o exercise3_24 && ./exercise3_24

exercise3_25.o:
	g++ exercise3_25.cpp -std=c++11 -o exercise3_25 && ./exercise3_25

exercise3_31.o:
	g++ exercise3_31.cpp -std=c++11 -o exercise3_31 && ./exercise3_31

exercise3_32.o:
	g++ exercise3_32.cpp -std=c++11 -o exercise3_32 && ./exercise3_32

exercise3_35.o:
	g++ exercise3_35.cpp -std=c++11 -o exercise3_35 && ./exercise3_35

exercise3_36.o:
	g++ exercise3_36.cpp -std=c++11 -o exercise3_36 && ./exercise3_36
	
exercise3_41.o:
	g++ exercise3_41.cpp -std=c++11 -o exercise3_41 && ./exercise3_41

exercise3_43.o:
	g++ exercise3_43.cpp -std=c++11 -o exercise3_43 && ./exercise3_43

exercise3_44.o:
	g++ exercise3_44.cpp -std=c++11 -o exercise3_44 && ./exercise3_44
	
exercise3_45.o:
	g++ exercise3_45.cpp -std=c++11 -o exercise3_45 && ./exercise3_45
