CC = g++

exercise4: exercise3_17.o exercise3_23.o exercise4_28.o inflation.o nutritionCalculator.o

exercise3_17.o:
	cd g++ exercise3_17.cpp -std=c++11 -o exercise3_17 && ./exercise3_17

exercise3_23.o:
	g++ exercise3_23.cpp -std=c++11 -o exercise3_23 && ./exercise3_23

exercise4_28.o:
	g++ exercise4_28.cpp -std=c++11 -o exercise4_28 && ./exercise4_28

inflation.o:
	g++ inflation.cpp -std=c++11 -o inflation && ./inflation
	
nutritionCalculator.o:
	g++ nutritionCalculator.cpp -std=c++11 -o nutritionCalculator && ./nutritionCalculator
