CC = g++

exercise10: exercise_10.o midtermRedo.o exercise10_14.o exercise10_30.o

exercise_10.o:
		g++ exercise_10.cpp -std=c++11 -o exercise_10.o && ./exercise_10.o
	
midtermRedo.o:
		g++ midtermRedo.cpp -std=c++11 -o midtermRedo.o && ./midtermRedo.o
	
exercise10_14.o:
		g++ exercise10_14.cpp -std=c++11 -o exercise10_14.o && ./exercise10_14.o
	
exercise10_30.o:
		g++ exercise10_30.cpp -std=c++11 -o exercise10_30.o && ./exercise10_30.o
	

