CC = g++

sampleEx1: exercise1_4.o exercise1_9.o exercise1_10.o exercise1_20.o exercise1_21.o exercise1_22.o exercise1_25.o

exercise1_4.o:
	g++ exercise1_4.cpp -o exercise1_4 && ./exercise1_4

exercise1_9.o:
	g++ exercise1_9.cpp -o exercise1_9 && ./exercise1_9

exercise1_10.o:
	g++ exercise1_10.cpp -o exercise1_10 && ./exercise1_10

exercise1_20.o:
	g++ exercise1_20.cpp -o exercise1_20 && ./exercise1_20

exercise1_21.o:
	g++ exercise1_21.cpp -std=c++11 -o exercise1_21 && ./exercise1_21

exercise1_22.o:
	g++ exercise1_22.cpp -std=c++11 -o exercise1_22 && ./exercise1_22

exercise1_25.o:
	g++ exercise1_25.cpp -std=c++11 -o exercise1_25 && ./exercise1_25
