CC = g++

sampleEx4: exercise4_21.o exercise4_22.o exercise4_31.o

exercise4_21.o:
	g++ exercise4_21.cpp -std=c++11 -o exercise4_21 && ./exercise4_21
	
exercise4_22.o:
	g++ exercise4_22.cpp -std=c++11 -o exercise4_22 && ./exercise4_22

exercise4_31.o:
	g++ exercise4_31.cpp -std=c++11 -o exercise4_31 && ./exercise4_31

