name: Exercise 10 programs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exercise10:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Running Exercise 10 makefile"
    - name: run programs
      run: cd ./exercise10 && make exercise10
