name: Exercise 4 programs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exercise4:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Running makefile"
    - name: run programs
      run: cd /exercise4 && make exercise4
