name: Hello world

on: [push]

jobs:
  HelloWorld:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - run: echo "Running makefile"
      - name: create prog
        run: g++ ./exercise3/helloworld.cpp -o ./exercise3/hello.out
