---
name: hello world

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: open exercise1 folder
      run: cd exercise1
    - name: run hello world code
      run: ./helloworld